site_name: 미쁨Edu ONLINE
site_description: Mippum's Home from MD Files
site_author: mippum

theme:
  name: material
  language: ko
  logo: assets/logo.png
  favicon: assets/logo.png

nav:
  - 홈: index.md
  - 서비스:
    - 듣기 트레이너: service/listening-trainer/index.md
    - 퀴즈: service/quiz/index.md
  - 전자책:
    - 자기긍정확언: epub/self-affirmation.md

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed

plugins:
  - search
  # - i18n:
  #     docs_structure: suffix
  #     languages:
  #       - name: 한국어
  #         locale: ko
  #         build: true
  #         default: true 
  #       - locale: en
  #         name: English
  #         build: true
  #         default: false
  #         site_name: "Documentation du plugin MkDocs static i18n (en)"
  #         site_description: "Description Française"

# 옵션: 배포 브랜치 설정 (기본값이 gh-pages)
# remote_branch: gh-pages

copyright:  © Mippum Edu Corporation. All rights reserved.

extra:
  generator: false
